# Generated by Django 3.2.9 on 2021-12-02 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Habitacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombrePersona', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=10)),
                ('numeroPersonas', models.IntegerField()),
                ('tipo', models.CharField(max_length=300)),
                ('dias', models.IntegerField()),
            ],
            options={
                'db_table': 'habitaciones',
            },
        ),
        migrations.CreateModel(
            name='Turismo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='')),
                ('nombre', models.CharField(max_length=100)),
                ('hora', models.CharField(max_length=100)),
                ('precio', models.PositiveIntegerField()),
                ('descripcion', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'turismo',
            },
        ),
    ]
